### ISSUE TITLE
Bad build when markdown files don't have extra whitespace after pound characters

### ISSUE THREAD

**Issue by nickdesaulniers** [stackgl/packages#11]
If you go to [my fork](http://nickdesaulniers.github.io/packages/), then click on [compile-shader](http://nickdesaulniers.github.io/packages/#nickdesaulniers/compile-shader), the following error is logged to the console: 

```
Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element.
```

I did not have any errors in my terminal when syncing or building.  Maybe some spurious whitespace in the wiki or is an issue?

**Comment by nickdesaulniers** [comment]
Indeed, [this change](https://github.com/nickdesaulniers/compile-shader/commit/099cb54e2b0b49e493e69196352d11a70d949023) seems to help.  So it seems like whatever markdown parser being used fails when the pound signs do not have a space immediately following them.  We should report this upstream.

**Comment by hughsk** [comment]
So the problem is caused by [mdast](https://github.com/wooorm/mdast) not recognising lines as headers if they're missing a space between the `#` and the content. This results in the repo's readme being stripped of all content, as the build script removes any content preceding the first header. The browser error comes through because React expects a DOM element there but there's nothing to include. Worth taking it up with wooorm to get his opinions on this :)

**Comment by wooorm** [comment]
Hai :)

Using ATX-headings without the space [should be avoided](http://spec.commonmark.org/0.21/#example-28). It makes differentiating between GitHub issues and headings hard! mdast’s [pedantic mode](https://github.com/wooorm/mdast/blob/master/doc/mdastsetting.7.md#pedantic) still supports it though!
