### ISSUE TITLE
strip images

### ISSUE THREAD

**Issue by mattdesl** [stackgl/packages#6]
Something I tend to do with a lot of packages is have a large image at the top to show it off. But in stack.gl/packages I'd rather it just show the real-time demo if there is one.

Maybe it would be good to have an image that gets stripped from the README and replaced by the iframe demo? e.g. The first image with `iframe-image` alt is replaced with the iframe content.

```md
![iframe-image](path/to/image.png)
```

**Comment by hughsk** [comment]
Currently this is halfway there: if you have an image in the first section of your README, i.e. between the first and second headings, it'll be [replaced with the iframe automatically](https://github.com/stackgl/packages/blob/gh-pages/build.js#L243-L261). That should cover the case where you have a big image up the top!

Being able to explicitly determine the image that gets replaced like that would be handy though – wanna send through a PR? Otherwise I can take a look at it in a couple days :)

**Comment by mattdesl** [comment]
ah didn't realize that was already in place. That covers my needs, so it's all good. :)
