### ISSUE TITLE
Move 'stackgl' config to environment variables

### ISSUE THREAD

**Issue by rreusser** [stackgl/packages#8]
This would make it possible to make fixes in stackgl/packages and use them downstream in scijs/packages. My favorite solution is something like [nconf](https://github.com/indexzero/nconf) with files `config.json.stackgl` and `config.json.scijs` (as long as no secrets). Then add:

```
# .gitignore:
config.json
```

And a build step:

``` bash
$ cp config.json.stackgl config.json
```

to apply specific config. This would basically make stackgl/packages and scijs/packages the same repo, which should probably be the goal unless there are other considerations.

**Comment by rreusser** [comment]
FWIW, if this all needs a pretty significant overhaul to work [ecosystem-docs](https://github.com/hughsk/ecosystem-docs) into the picture, I'm totally willing to take a stab at that. I have a few more days of freedom before work starts again but don't want to step on any toes.

**Comment by hughsk** [comment]
Hey @rreusser! I'm halfway through a rewrite of the packages site that fully takes advantage of ecosystem-docs and has a nicer, cleaner UI. Things've been slow for me lately because I've been travelling, but starting today I have a couple of weeks of stability before I take off again :tada:

I'm gonna take a shot at finishing up the site tonight, but if I don't then I'll put the code up so we can work towards getting something together quickly. Shouldn't be too hard to have a `config.json` file (or `config.js` even) to have things easily tweakable for different orgs. It'd be really nice to have something close to fork-n-go for others too :)

**Comment by rreusser** [comment]
No worries! Please don't rush on my account! I start a new job Monday, so I was racing to get some of these messy things in order so that it's not sooo difficult keep to squeezing in some straightforward low-hanging fruit. Thanks and looks great so far!

**Comment by hughsk** [comment]
No problem at all! :)

I've just pushed the new site to the master branch, everything should be a little more pleasant now. If all goes to plan, you should be able to fork this repository to scijs and start using it pretty quickly. There's some instructions [in the README](https://github.com/stackgl/packages/tree/master#build-your-own-list) but the key files to update are [config.js](/stackgl/packages/blob/master/config.js) and [intro.md](/stackgl/packages/blob/master/intro.md).

This way, we can update the features/design of this site and still merge those into scijs' packages site too without merge conflict headaches. Let me know if this works! :D
